apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beepboopbf_application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HatsuneKareshi/argocd-app-mmc.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: beepboopbf_namespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true